---
stages:
  - name: "lint"
  - name: "test"
  - name: "deploy-github"
    if: "tag IS present"
  - name: "deploy-pypi"
    if: "tag IS present"

language: "python"
python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9

services:
  - "docker"

before_script:
  - "pip install invoke poetry toml"
  - "invoke build --no-cache"
script:
  - "invoke pytest"

jobs:
  include:
    - stage: "lint"
      before_script:
        - "pip install invoke toml docker-compose"
        - "invoke build"
      script:
        - "invoke black"
        - "invoke bandit"
        - "invoke pydocstyle"
        - "invoke flake8"
        - "invoke yamllint"
        - "invoke pylint"

    - stage: "deploy-github"
      before_script:
        - "pip install --upgrade pip"
        - "pip install poetry"
      script:
        - "poetry version $TRAVIS_TAG"
        - "poetry build"
      deploy:
        provider: "releases"
        api_key: "$GITHUB_AUTH_TOKEN"
        file_glob: true
        file: "dist/*"
        skip_cleanup: true
        "on":
          all_branches: true

    - stage: "deploy-pypi"
      before_script:
        - "pip install --upgrade pip"
        - "pip install poetry"
      script:
        - "echo Deploying the release to PyPI"
        - "poetry version $TRAVIS_TAG"
      deploy:
        provider: "script"
        skip_cleanup: true
        script: "poetry publish --build -u __token__ -p $PYPI_TOKEN"
        "on":
          all_branches: true
